### ISSUE TITLE
file transfers to x-plus3. 

### ISSUE THREAD

**Issue by WiskyBlackOut** [QIDITECH/QIDI_PLUS3#17]
Totally new to this. Cant figure out how to transfer files or find any basic instructions on ways to transfer files to printer

**Comment by QIDITECH** [comment]
The guide in the slicing software may help you.
![image](https://github.com/QIDITECH/QIDI_PLUS3/assets/37525539/9fc268e8-aa2d-4dbc-b722-d058499ab271)

**Comment by WiskyBlackOut** [comment]
Okay were do I access that? No idea how to get there and searching for
qidislicer doesnt realy result anything.

**Comment by CChen616** [comment]
You can download the Qidi Slicer here:
https://qidi3d.com/pages/software-firmware

Additionally, after connecting your printer to Wi-Fi, you can try accessing the printer's Fluidd page from your PC or your mobile phone that connected to the same Wi-Fi network. Simply open a browser and go to:
```
http://{printer's IP address}:10088
```

If you're completely new to 3D printing, you might need to spend some time exploring the Fluidd interface to become familiar with it.

Happy printing!

**Comment by WiskyBlackOut** [comment]
Any resources to learn and reference how to use the qidislicer program.
