### ISSUE TITLE
Fluidd Gcode Viewer 

### ISSUE THREAD

**Issue by ADRS55** [QIDITECH/QIDI_PLUS3#18]
G code preview in fluidd does not show the entire print area, part of it is missing.

**Comment by CChen616** [comment]
Are you referring to the thumbnail of the model? If so, could you please let us know which slicing software you're using and also send us a copy of the G-code?

**Comment by ADRS55** [comment]
No, not thumbnails. I'm referring to the fluidd's gcode viewer, layer progress 2D visualizer.
![slicer](https://github.com/QIDITECH/QIDI_PLUS3/assets/158287971/97487278-7c30-4a20-a3c4-0a86f24213ad)
![fluidd](https://github.com/QIDITECH/QIDI_PLUS3/assets/158287971/fae91b3c-9679-4543-bd6b-f5222b6ca262)

**Comment by CChen616** [comment]
Due to Fluidd using the toolhead's minimum and maximum movement ranges to determine the display range for G-code previews, there may be discrepancies with the actual size of the heatbed and what is shown in the slicing software.

As we aim to provide the majority of users with an authentic Fluidd experience, we might not modify this aspect.

**Comment by ADRS55** [comment]
I didn't change anything in printer.cfg. 
Information returned from url:

        "axis_minimum": [
          -11,
          -24,
          -6,
          0
        ],
        "stalls": 0,
        "axis_maximum": [
          280,
          280,
          280,
          0
        ],

From my understanding, it should be correct.
But I think it's a bug in fluidd, because today I found this:
[https://github.com/fluidd-core/fluidd/pull/731](url)
It should be fixed in newer versions. Do you plan to update fluidd to a newer version in future releases?
​

**Comment by CChen616** [comment]
Thank you for providing a solution!

Currently, it's challenging to update fluidd via update packages. However, you can manually update fluidd by referring to the instructions in the "fluidd" section at:

https://docs.fluidd.xyz/updates/manual

In our machines, fluidd is located at 
```
/home/mks/fluidd/
```
Please do not update other components such as Klipper and Moonraker, as this will cause the printer to malfunction.

**Comment by ADRS55** [comment]
I did a manual update as you recommended and the fluidd gcode preview is now working correctly!
![new_fluidd](https://github.com/QIDITECH/QIDI_PLUS3/assets/158287971/eeed0784-fa3a-4a3f-bbf1-5a677388e7d3)


Thank you for your support!

**Comment by dleffler** [comment]
As a note, if you manually update fluidd, you'll receive warnings on the fluidd interface and warning about unsupported firmware when you ssh in.
