### ISSUE TITLE
Add 0.005 or lower option for Z offset

### ISSUE THREAD

**Issue by Lightning2X** [QIDITECH/QIDI_PLUS3#2]
Currently the lowest Z offset is 0.01 But for exact precision you'd preferably also have 0.005 like the fluidd web interface has:
![image](https://github.com/QIDITECH/QIDI_PLUS3/assets/32514161/6c7043e6-7d6c-4e43-9f04-3cb18b92ed93). 
Since its currently impossible to store the z offset from the fluidd web interface (from what I've found) it would be nice if this is added to the firmware

**Comment by QIDITECH** [comment]
The z-offset on fluidd works fine, it's just that 0.005mm is too small to tell if it works.

I'm very sorry we won't be adding 0.005 to the firmware, it might be misleading for newcomers.
