### ISSUE TITLE
Support cold-pull cleaning

### ISSUE THREAD

**Issue by jrice128** [QIDITECH/QIDI_PLUS3#25]
When switching between high and low extrusion temp filaments, it can be advantageous to use cleaning filament to purge and clean the nozzle.  Part of this process can involve doing a cold-pull with the cleaning filament.  This is also useful for periodic maintenance to remove any particulate, burnt-on filament, or any other such debris from the nozzle.  With the current firmware, there is no way to do this without fighting against the extruder, as:

1. There doesn't appear to be a way to de-power the extruder gears (unless the stepper motor GUI button also works on the extruder?)
2. The Load menu retraction controls will not allow filament retraction at a hotend temp below 170C

It would be great if there was a way either to unlock the extruder gears in the UI, or if the warning that popped up when trying to retract under 170 C instead had an additional option of "Proceed with Caution".

**Comment by CChen616** [comment]
In `printer.cfg`, there is a section:
```
[extruder]
...
min_temp: 0
max_temp: 360
min_extrude_temp: 175
...
```
The `min_extrude_temp` represents the minimum temperature at which the extruder is allowed to extrude. Currently, you can manually modify `min_extrude_temp` and then restart Klipper or the printer to apply the change. For safety reasons and applicability, we may not add support for cold-pulling on the display.
