### ISSUE TITLE
Why not heating bed and nozzle at same time?

### ISSUE THREAD

**Issue by majo1604** [QIDITECH/QIDI_PLUS3#26]
Before printing, the bed is first heated up and then the nozzle. Couldn't do both at the same time? It would save some time.

**Comment by SIGAN** [comment]
May I suggest to not do that. Otherwise material will start dropping and entire bed will be in it. Heating up nozzle is quick.
Also you can turn on nozzle heater in the UI before printing.

**Comment by CChen616** [comment]
Indeed, as mentioned in the last comment, heating the nozzle is much faster than heating the bed, it results in the nozzle being in a heated state for an extended period, leading to filament leakage. Currently, we are not considering adding a simultaneous heating feature.
