### ISSUE TITLE
Provision of HMI files

### ISSUE THREAD

**Issue by leadustin** [QIDITECH/QIDI_PLUS3#28]
Is it possible to provide the HMI files of the display? They are included in the Q1 github but are missing for Max3/Plus3. The support for the Plus3 does not seem to be able to provide them.

**Comment by CChen616** [comment]
The Plus3 and Max3 UI files have been uploaded to the latest branch

**Comment by leadustin** [comment]
> The Plus3 and Max3 UI files have been uploaded to the latest branch

I don't mean the . TFT. I would like to have the . HMI to edit them in the editor. This file is not available in the Max3/Plus3 releases.

**Comment by CChen616** [comment]
It's both in there 
![image](https://github.com/QIDITECH/QIDI_PLUS3/assets/88018764/44de6268-c135-45c2-bb7d-98b31549ef06)
