### ISSUE TITLE
update error！ Already in a manual Z probe. Use ABORT to abort it.

### ISSUE THREAD

**Issue by Lovelace3314** [QIDITECH/QIDI_PLUS3#42]
update fw from V4.2.13 to V4.2.15.I found that I could not complete the platform calibration,I resolved the problem by modifying the configuration file.

<img width="479" alt="b3a84d70c8968b738d8cea67e3f5456" src="https://github.com/user-attachments/assets/f59912e3-0091-4dcc-9f61-f134245373e3">

![image](https://github.com/user-attachments/assets/61c321b8-8172-44ca-9c58-603e001af355)

![image](https://github.com/user-attachments/assets/607487f2-0348-4d52-b4a1-0506e02886da)

**Comment by Lovelace3314** [comment]
[gcode_macro M4029]
gcode:
    BED_MESH_CLEAR
    G91 
    G1 Z10 F600
    G90
    G28
    G1 X{printer.toolhead.axis_maximum.x/2 - printer.probe["x_offset"]} Y{printer.toolhead.axis_maximum.y/2 - printer.probe["y_offset"]} F7800
    G1 Z15 F600
    ABORT
    PROBE_CALIBRATE
    ABORT
    G0 Z0

**Comment by QIDITECH** [comment]
Where did you download the firmware? This is an incorrect profile that we never uploaded.

**Comment by Lovelace3314** [comment]
This error exists in the file I downloaded on October 18th, and the problem has been fixed in the file I downloaded today.

![QQ_1730165412098](https://github.com/user-attachments/assets/12a4fc56-3bc6-4735-a13e-f1110f818d5e)

![QQ_1730165478145](https://github.com/user-attachments/assets/42840a19-342d-4d2c-986c-67c1dfc2ae94)

![QQ_1730166055838](https://github.com/user-attachments/assets/962ef276-c711-408a-bc2d-30929bd7c1ac)

**Comment by Lovelace3314** [comment]
The date of revision of the two documents does not coincide.
Good thing you've solved the problem.
I used an old upgrade package to cause the above problem.

![QQ_1730166539617](https://github.com/user-attachments/assets/0eda613c-bc7e-457b-abc5-2e1e53407fc6)

**Comment by QIDITECH** [comment]
We replaced the wrong version as soon as we uploaded it. Your action was too fast.
