### ISSUE TITLE
Bed temperature with negative value after v4.2.15 upgrade

### ISSUE THREAD

**Issue by ziggornif** [QIDITECH/QIDI_PLUS3#44]
Hello, 

I just updated my X-Plus 3 to version 4.2.15.

With this new version, my bed temperature is negative.

![Screenshot 2024-11-04 at 16 54 30](https://github.com/user-attachments/assets/b0241cc6-68c9-49e7-a93d-5c94dc47e545)

How can I fix this ?

**Comment by QIDITECH** [comment]
Please check that the temperature sensor of the heater bed is properly connected.
If it is damaged, replace it with a new one.
