### ISSUE TITLE
Replacing TMC2209 with TMC2240

### ISSUE THREAD

**Issue by leadustin** [QIDITECH/QIDI_PLUS3#46]
Hello,

is it possible to replace the original TMC2209 with TMC2240? Are the pins the same? I know that I have to make changes to the printer.cfg. I just want to know if there is compatibility with the mainboard.
Thx

**Comment by QIDITECH** [comment]
The motor drive is integrated on the motherboard and cannot be replaced.

**Comment by leadustin** [comment]
> The motor drive is integrated on the motherboard and cannot be replaced.

So the drivers are soldered on directly? What would be the process for a defective driver? Buying a new mainboard is out of the question. Can the defective driver then be desoldered and replaced with a 2240?

**Comment by QIDITECH** [comment]
Sorry, the number of pins in the two chips is different, so this is not possible.
