### ISSUE TITLE
Checksum Error with 4.2.12

### ISSUE THREAD

**Issue by ArnaudSibille** [QIDITECH/QIDI_PLUS3#8]
I have the same probleme that previous user : Checksum error after installing 4.2.12 version.  Now printer stuck on "Data Error" when booting.
It  seems there is a solution by loading directly the firmware using SD card reader from display card.
Could you give more details please.

Sincerely 

A. Sibille

**Comment by QIDITECH** [comment]
Data loss due to too long screen cable.
Please contact our after-sales service and they will give you detailed tutorials.
https://qidi3d.com/pages/warranty-policy-after-sales-support
Github does not support this format file, so we cannot serve you on Github.
